import random

f = open('randout.inc', 'w')

str = "; Random Number Table generated by Cthulhu32's ran_gen.py\n"

for i in xrange(0, 260):
	if i % 16 == 0:
		f.write(str)
		str = "\n.db "
	str += "$%02x, "%(random.randint(0,5))
	
f.close()
	