.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $000
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $001
.db $01 $FE $00 $00 $03 $FC $00 $00 $07 $F8 $00 $00 $0F $F0 $00 $00 $1F $E0 $00 $00 $3F $C0 $00 $00 $7F $80 $00 $00 $FF $00 $00 $00
; Tile index $002
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $003
.db $01 $FE $00 $00 $03 $FC $00 $00 $07 $F8 $00 $00 $0F $F0 $00 $00 $1F $E0 $00 $00 $3F $C0 $00 $00 $7F $80 $00 $00 $FF $01 $01 $01
; Tile index $004
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $FF $FF $FF
; Tile index $005
.db $FF $00 $00 $00 $FE $01 $00 $00 $FC $03 $00 $00 $F8 $07 $00 $00 $F0 $0F $00 $00 $E0 $1F $00 $00 $C0 $3F $00 $00 $FF $FF $FF $FF
; Tile index $006
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $FF $FF $FF $FF
; Tile index $007
.db $01 $FE $00 $00 $03 $FC $00 $00 $07 $F8 $00 $00 $0F $F0 $00 $00 $1F $E0 $00 $00 $3F $C0 $00 $00 $7F $80 $00 $00 $FF $FF $FF $FF
; Tile index $008
.db $FF $01 $01 $01 $FF $01 $01 $01 $FF $01 $01 $01 $FF $01 $01 $01 $FF $01 $01 $01 $FF $01 $01 $01 $FF $01 $01 $01 $FF $01 $01 $01
; Tile index $009
.db $FF $00 $00 $00 $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F
; Tile index $00A
.db $00 $FF $00 $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $00B
.db $01 $FE $00 $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $00C
.db $FF $00 $00 $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $00D
.db $FF $01 $01 $01 $FF $FD $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD
; Tile index $00E
.db $01 $FE $00 $00 $03 $FC $00 $00 $07 $F8 $00 $00 $0F $F0 $00 $00 $1F $E0 $00 $00 $3E $C1 $00 $1F $78 $87 $00 $7F $F0 $8C $83 $7F
; Tile index $00F
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $00 $FC $03 $FF $02 $F8 $05 $FF $03 $01 $FF $FC
; Tile index $010
.db $FF $00 $00 $00 $FE $01 $00 $00 $FC $03 $00 $00 $F8 $07 $00 $00 $F0 $0F $00 $00 $00 $00 $FF $FF $55 $00 $AA $FF $FF $AA $FF $00
; Tile index $011
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $00 $FF $FF $55 $00 $AA $FF $FF $AA $FF $00
; Tile index $012
.db $01 $FE $00 $00 $03 $FC $00 $00 $07 $F8 $00 $00 $0F $F0 $00 $00 $1F $E0 $00 $00 $00 $00 $FF $FF $55 $00 $AA $FF $FF $AA $FF $00
; Tile index $013
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $00 $00 $FF $FF $55 $00 $AA $FF $FF $AA $FF $00
; Tile index $014
.db $FF $00 $00 $00 $FE $01 $00 $00 $FC $03 $00 $00 $F8 $07 $00 $00 $F0 $0F $00 $00 $00 $3F $C0 $FF $40 $1F $A0 $FF $C0 $80 $FF $3F
; Tile index $015
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $78 $87 $00 $F8 $1E $E1 $00 $FE $0F $31 $C1 $FE
; Tile index $016
.db $FF $01 $01 $01 $FF $01 $01 $01 $FD $03 $01 $01 $F9 $07 $01 $01 $F1 $0F $01 $01 $E1 $1F $01 $01 $C1 $3F $01 $01 $81 $7F $01 $01
; Tile index $017
.db $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F
; Tile index $018
.db $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $019
.db $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD
; Tile index $01A
.db $01 $FE $00 $01 $03 $FD $01 $00 $07 $FA $02 $01 $0F $F2 $02 $01 $1E $E3 $02 $01 $3F $C0 $00 $03 $7E $81 $00 $03 $FF $00 $04 $03
; Tile index $01B
.db $C3 $3F $03 $FC $83 $78 $07 $FC $81 $7C $03 $FF $01 $FC $02 $FF $01 $F1 $0F $FE $79 $D0 $5E $A7 $79 $A8 $7F $87 $18 $C0 $27 $FF
; Tile index $01C
.db $E0 $70 $6F $9F $E0 $70 $EF $1F $A0 $40 $3F $FF $E0 $00 $9F $7F $E0 $20 $FF $1F $E0 $30 $EF $1F $E0 $90 $6F $1F $70 $40 $BF $9F
; Tile index $01D
.db $80 $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $80 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $01E
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $01F
.db $FF $00 $00 $80 $FF $80 $80 $00 $FF $40 $40 $80 $FF $40 $40 $80 $7F $C0 $40 $80 $FF $00 $00 $C0 $7F $80 $00 $C0 $FF $00 $20 $C0
; Tile index $020
.db $FF $FF $FF $FF $FE $81 $80 $80 $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $BF $FF $BF $BF
; Tile index $021
.db $FF $FF $FF $FF $00 $FF $00 $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $022
.db $FF $FF $FF $FF $03 $FC $00 $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $023
.db $FF $FF $FF $FF $FF $00 $00 $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $024
.db $FF $FF $FF $FF $FE $01 $00 $00 $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF $FF
; Tile index $025
.db $FF $FF $FF $FF $03 $FC $00 $00 $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE
; Tile index $026
.db $01 $FF $01 $01 $01 $FF $01 $01 $01 $FF $01 $01 $01 $FF $01 $01 $01 $FF $01 $01 $01 $FF $01 $01 $01 $FF $01 $01 $01 $FF $01 $01
; Tile index $027
.db $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $FF $7F $7F $7F
; Tile index $028
.db $FD $FF $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD
; Tile index $029
.db $FE $05 $04 $03 $FE $05 $04 $03 $FE $05 $04 $03 $FF $00 $00 $07 $FE $05 $04 $03 $FE $01 $00 $07 $FE $01 $08 $07 $FE $01 $08 $07
; Tile index $02A
.db $3C $A4 $77 $CB $7C $A6 $7D $C3 $3E $D6 $2F $E1 $1E $F6 $2F $E1 $1C $F4 $1B $F3 $0C $F1 $0E $FF $00 $FE $01 $FF $00 $F8 $07 $FF
; Tile index $02B
.db $60 $00 $FC $FF $00 $00 $F9 $FE $00 $01 $F7 $F8 $00 $07 $F3 $F8 $0A $01 $F8 $FC $00 $02 $FE $FF $3D $00 $FF $FF $60 $40 $FF $BF
; Tile index $02C
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $02D
.db $7F $A0 $20 $C0 $7E $A1 $20 $C0 $7C $A3 $20 $C0 $F8 $07 $00 $E0 $70 $AF $20 $C0 $60 $9F $00 $E0 $70 $8F $10 $E0 $70 $8F $10 $E0
; Tile index $02E
.db $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE
; Tile index $02F
.db $FF $80 $80 $80 $FE $81 $80 $80 $FC $83 $80 $80 $F8 $87 $80 $80 $F0 $8F $80 $80 $E0 $9F $80 $80 $C0 $BF $80 $80 $80 $FF $80 $80
; Tile index $030
.db $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD
; Tile index $031
.db $FE $01 $08 $07 $FE $09 $08 $07 $FE $09 $08 $07 $FE $09 $08 $07 $FC $0B $08 $07 $EC $1B $08 $07 $CC $3B $08 $07 $8C $7B $08 $07
; Tile index $032
.db $00 $F4 $0B $FF $00 $C0 $3F $FF $00 $F0 $0F $FF $00 $F8 $07 $FF $02 $E1 $1C $FF $1F $CB $2F $F0 $30 $A7 $7D $CF $39 $E7 $3D $CF
; Tile index $033
.db $E0 $40 $80 $9F $DE $41 $80 $80 $7F $7F $80 $80 $3F $58 $BF $C0 $1E $01 $FF $FF $86 $01 $FE $7F $8F $00 $FB $7C $8F $09 $FF $73
; Tile index $034
.db $70 $8F $10 $E0 $70 $9F $10 $E0 $70 $9F $10 $E0 $70 $9F $10 $E0 $30 $DF $10 $E0 $30 $DF $10 $E0 $30 $DF $10 $E0 $30 $DF $10 $E0
; Tile index $035
.db $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF
; Tile index $036
.db $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $FF $7F $7F $7F $80 $7F $00 $00
; Tile index $037
.db $FF $FD $FD $FD $FF $FD $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $FD $FF $FD $FD $81 $7F $01 $01
; Tile index $038
.db $0C $FB $08 $07 $0C $FB $08 $07 $0C $FB $08 $07 $0C $FB $08 $07 $0C $FB $08 $07 $0C $FB $08 $07 $0C $FB $08 $07 $0C $FB $08 $07
; Tile index $039
.db $1F $DF $30 $E0 $08 $E3 $1C $FF $0F $EA $1C $F1 $0E $F5 $04 $FB $0B $E0 $18 $F7 $1F $D1 $3F $E0 $1F $C0 $3F $E0 $0F $FA $05 $F0
; Tile index $03A
.db $87 $85 $7B $78 $87 $01 $FE $FC $02 $01 $FF $FF $0F $00 $FF $FF $1F $08 $FF $F0 $1F $00 $FF $F1 $1E $01 $FF $F1 $1F $0B $F4 $F0
; Tile index $03B
.db $31 $DE $10 $E0 $33 $DC $10 $E0 $37 $D8 $10 $E0 $3F $D0 $10 $E0 $3F $D0 $10 $E0 $3F $D0 $10 $E0 $3F $D0 $10 $E0 $3F $D0 $10 $E0
; Tile index $03C
.db $FF $01 $01 $01 $FE $01 $00 $00 $FC $03 $00 $00 $F8 $07 $00 $00 $F0 $0F $00 $00 $E0 $1F $00 $00 $C0 $3F $00 $00 $80 $7F $00 $00
; Tile index $03D
.db $0C $FB $08 $07 $0C $FB $08 $07 $0C $FB $08 $07 $0C $FB $08 $07 $1C $EB $08 $07 $3C $CB $08 $07 $7E $89 $08 $07 $FE $09 $08 $07
; Tile index $03E
.db $07 $D6 $2F $F9 $00 $F0 $0F $FF $1F $E0 $10 $FF $1F $CC $3F $E0 $3B $C0 $1E $E7 $3F $D5 $2F $E0 $1F $A8 $5F $F0 $00 $F0 $0F $FF
; Tile index $03F
.db $04 $03 $F8 $FF $03 $00 $FF $FF $80 $07 $7F $FF $CC $41 $7F $BF $CF $A5 $DF $38 $E7 $07 $FF $3F $CF $81 $F1 $7E $07 $00 $FF $FF
; Tile index $040
.db $3F $D0 $10 $E0 $3F $D0 $10 $E0 $3F $D0 $10 $E0 $3F $D0 $10 $E0 $3F $D0 $10 $E0 $3F $D0 $10 $E0 $7F $90 $10 $E0 $7F $90 $10 $E0
; Tile index $041
.db $FE $09 $08 $07 $FE $01 $08 $07 $FE $01 $08 $07 $FE $01 $08 $07 $FE $01 $08 $07 $FE $05 $0C $03 $FE $0D $04 $03 $FE $0D $04 $03
; Tile index $042
.db $00 $D0 $2F $FF $00 $FA $05 $FF $01 $F8 $06 $FF $03 $FA $07 $FC $02 $F1 $0E $FC $03 $F2 $0E $FC $39 $C9 $0F $F6 $F8 $E0 $FF $07
; Tile index $043
.db $14 $00 $FB $FF $BF $1C $E7 $63 $09 $12 $2E $FF $33 $E1 $3D $1E $27 $81 $FF $1C $37 $02 $FF $1C $C1 $83 $7F $3E $80 $01 $FF $FF
; Tile index $044
.db $7F $90 $10 $E0 $7E $81 $10 $E0 $7C $83 $10 $E0 $78 $87 $10 $E0 $70 $8F $10 $E0 $70 $AF $30 $C0 $70 $BF $20 $C0 $70 $BF $20 $C0
; Tile index $045
.db $FE $0D $04 $03 $FE $0D $04 $03 $FE $05 $04 $03 $FF $04 $04 $03 $F7 $08 $04 $03 $E7 $1A $06 $01 $C7 $3A $06 $01 $87 $7A $06 $01
; Tile index $046
.db $E8 $D0 $EF $37 $E8 $B0 $EF $37 $D8 $63 $3C $A7 $F9 $44 $B3 $8F $32 $F1 $1E $CF $5D $81 $27 $FF $79 $7F $9F $87 $0B $A3 $5F $FF
; Tile index $047
.db $03 $00 $FC $FF $23 $9F $6F $FF $9F $3F $FF $FF $1F $BF $DE $FE $9E $6F $CF $FF $0E $3B $EA $F5 $86 $98 $FF $FF $E0 $D8 $D8 $FF
; Tile index $048
.db $70 $BF $20 $C0 $70 $BF $20 $C0 $60 $BF $20 $C0 $E0 $3F $20 $C0 $E0 $1F $20 $C0 $E0 $5F $60 $80 $E0 $5F $60 $80 $E0 $5F $60 $80
; Tile index $049
.db $07 $FA $06 $01 $07 $FE $02 $01 $07 $FF $03 $00 $07 $FF $03 $00 $07 $FF $03 $00 $07 $FF $03 $00 $07 $FF $03 $00 $07 $FF $03 $00
; Tile index $04A
.db $07 $F2 $0E $FF $0E $F2 $0E $FE $83 $77 $0B $FF $81 $73 $0F $FF $C3 $3F $07 $FD $C3 $89 $87 $7E $91 $91 $87 $7F $C0 $80 $BB $07
; Tile index $04B
.db $C0 $F0 $57 $78 $E0 $5B $F7 $70 $E4 $5A $D9 $78 $80 $FC $DC $FF $25 $F2 $BF $FF $49 $6E $FF $FF $DF $DF $FF $FF $3F $FF $BE $FE
; Tile index $04C
.db $E1 $5E $60 $80 $E3 $7C $40 $80 $E7 $F8 $C0 $00 $EF $F0 $C0 $00 $FF $E0 $C0 $00 $FF $E0 $C0 $00 $FF $E0 $C0 $00 $FF $E0 $C0 $00
; Tile index $04D
.db $07 $FF $03 $00 $07 $FE $02 $01 $07 $FE $02 $01 $0F $F6 $02 $01 $1F $E6 $02 $01 $3F $C6 $02 $01 $7F $86 $02 $01 $FF $06 $02 $01
; Tile index $04E
.db $D0 $90 $AD $13 $8C $8D $B0 $4F $C0 $56 $4C $A1 $E2 $2C $20 $D1 $7F $90 $10 $EF $3F $C0 $00 $FF $8F $70 $00 $FF $9F $60 $00 $FF
; Tile index $04F
.db $3F $57 $DF $EF $27 $13 $FB $FC $07 $00 $FF $FF $01 $C0 $3F $FF $01 $E0 $1F $FF $C0 $31 $0F $FF $F6 $0B $07 $FF $F7 $0B $03 $FE
; Tile index $050
.db $FF $E0 $C0 $00 $FF $60 $40 $80 $FF $60 $40 $80 $FF $60 $40 $80 $FF $60 $40 $80 $FF $60 $40 $80 $FF $60 $40 $80 $FF $60 $40 $80
; Tile index $051
.db $FF $06 $02 $01 $FF $06 $02 $01 $FF $04 $00 $03 $FF $06 $02 $01 $FF $06 $02 $01 $FF $06 $02 $01 $FF $06 $02 $01 $FF $02 $06 $01
; Tile index $052
.db $7B $BE $3A $FD $6D $E7 $77 $BE $BC $3A $7B $D7 $1A $FF $1F $EF $0F $EF $1F $F0 $80 $70 $0F $FF $0C $E0 $1F $F3 $13 $EF $1D $EC
; Tile index $053
.db $FE $01 $02 $FD $7C $83 $00 $FF $04 $7B $80 $FF $00 $80 $7E $FF $02 $02 $F9 $FE $0C $01 $FB $F8 $04 $09 $FB $F8 $04 $03 $FC $FC
; Tile index $054
.db $FF $60 $40 $80 $FE $61 $40 $80 $FC $23 $00 $C0 $F8 $67 $40 $80 $F0 $6F $40 $80 $E0 $7F $40 $80 $E0 $7F $40 $80 $E0 $5F $60 $80
; Tile index $055
.db $FF $02 $06 $01 $FF $00 $04 $03 $FF $02 $06 $01 $FF $00 $04 $03 $F7 $0A $06 $01 $E7 $1A $06 $01 $C7 $3A $06 $01 $87 $7A $06 $01
; Tile index $056
.db $3F $9F $7E $DE $3F $9F $5F $FE $3F $BF $7F $DE $3F $DE $3F $DE $1B $DA $3F $EE $19 $D6 $3B $EE $1E $DF $3E $EF $2F $DF $1F $FF
; Tile index $057
.db $06 $01 $FF $FF $03 $80 $7F $FF $03 $00 $FF $FF $07 $00 $FF $FF $03 $00 $FF $FF $87 $00 $FF $FF $9F $00 $73 $FF $BE $8F $7F $61
; Tile index $058
.db $E0 $5F $60 $80 $E0 $1F $20 $C0 $E0 $5F $60 $80 $E0 $1F $20 $C0 $E0 $5F $60 $80 $E0 $5F $60 $80 $E0 $5F $60 $80 $E0 $5F $60 $80
; Tile index $059
.db $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $FF $80 $80 $80 $FF $FF $FF $FF
; Tile index $05A
.db $FF $FE $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $C0 $3F $00 $00 $FF $FF $FF $FF
; Tile index $05B
.db $07 $FE $02 $01 $07 $FE $02 $01 $07 $FE $02 $01 $07 $FE $02 $01 $07 $FE $02 $01 $07 $FE $02 $01 $07 $FE $02 $01 $07 $FE $02 $01
; Tile index $05C
.db $3F $DF $3F $DF $3F $CF $0F $FF $1B $CD $3E $E6 $0F $E2 $17 $F9 $00 $F0 $0F $FF $00 $C8 $37 $FF $0B $F5 $09 $FE $0E $E0 $1F $F1
; Tile index $05D
.db $F2 $3F $F2 $4D $FE $A4 $77 $49 $3E $1F $E3 $E1 $17 $08 $F7 $FF $0F $00 $FF $FF $07 $00 $FF $FF $C1 $06 $3C $FF $EF $64 $FF $18
; Tile index $05E
.db $E1 $7E $40 $80 $E3 $7C $40 $80 $E7 $78 $40 $80 $EF $70 $40 $80 $FF $60 $40 $80 $FF $60 $40 $80 $FF $60 $40 $80 $FF $60 $40 $80
; Tile index $05F
.db $07 $FE $02 $01 $07 $FE $02 $01 $03 $FA $02 $01 $0F $F2 $02 $01 $1F $E2 $02 $01 $3F $C0 $02 $01 $7F $80 $02 $01 $FF $00 $02 $01
; Tile index $060
.db $0E $EB $17 $F1 $0F $EE $19 $F0 $07 $F3 $0F $FC $01 $F0 $0F $FF $03 $F4 $08 $FF $0F $EC $1E $F1 $1F $EB $17 $F1 $8F $64 $1A $F1
; Tile index $061
.db $E7 $0C $FB $18 $EF $62 $B9 $1C $AD $82 $FE $7F $0E $01 $FF $FF $E6 $01 $3E $FF $FF $20 $BB $5C $E7 $0C $FB $18 $FF $46 $BD $18
; Tile index $062
.db $FF $60 $40 $80 $FF $60 $40 $80 $DF $40 $40 $80 $FF $40 $40 $80 $FF $40 $40 $80 $FF $00 $40 $80 $FF $00 $40 $80 $FF $00 $40 $80
; Tile index $063
.db $FF $00 $02 $01 $FF $00 $02 $01 $FF $01 $03 $00 $FF $01 $03 $00 $FF $03 $01 $00 $FF $03 $01 $00 $FF $03 $01 $00 $FF $03 $01 $00
; Tile index $064
.db $8F $70 $0B $FC $81 $58 $27 $FF $03 $F0 $0C $FF $87 $7B $07 $F8 $8F $4B $37 $F1 $9E $68 $17 $F1 $8F $71 $0E $F8 $83 $7B $07 $FC
; Tile index $065
.db $F1 $05 $BF $7E $86 $01 $FF $FF $84 $03 $7E $FF $FB $83 $9F $7C $E7 $2C $FB $18 $F7 $2C $DB $18 $E3 $46 $FF $3C $CC $03 $FF $7F
; Tile index $066
.db $FF $00 $40 $80 $FE $01 $40 $80 $FC $83 $C0 $00 $F8 $87 $C0 $00 $F0 $CF $80 $00 $E0 $DF $80 $00 $C0 $FF $80 $00 $C0 $FF $80 $00
; Tile index $067
.db $FF $01 $01 $00 $FF $01 $01 $00 $FD $02 $01 $00 $F9 $06 $01 $00 $F1 $0E $01 $00 $E1 $1E $01 $00 $C1 $3E $01 $00 $81 $7F $00 $00
; Tile index $068
.db $83 $69 $15 $FE $83 $72 $0E $FD $86 $62 $1F $F9 $84 $63 $1E $FB $81 $75 $08 $FC $83 $70 $0E $FF $C0 $B8 $87 $7F $C0 $B0 $8F $7F
; Tile index $069
.db $84 $83 $FF $7F $87 $40 $3D $FE $E7 $C8 $FF $38 $C7 $0C $FB $B8 $87 $C1 $3E $7C $8C $03 $FF $FF $03 $00 $FF $FF $00 $06 $F9 $FF
; Tile index $06A
.db $80 $FF $80 $00 $80 $FF $80 $00 $80 $7F $80 $00 $80 $7F $80 $00 $80 $7F $80 $00 $80 $7F $80 $00 $80 $7F $80 $00 $80 $FF $00 $00
; Tile index $06B
.db $01 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $06C
.db $C1 $B8 $86 $7F $C7 $B2 $8F $7C $C4 $B4 $8C $78 $C5 $30 $8C $79 $C4 $30 $8C $7C $C2 $38 $87 $7F $C1 $7C $C2 $3F $C1 $F8 $47 $3F
; Tile index $06D
.db $5F $BA $1A $E5 $CE $11 $75 $FB $E3 $D1 $63 $30 $7F $58 $77 $20 $70 $01 $71 $71 $F0 $2F $3F $DF $B7 $E0 $BF $5F $FF $40 $9F $3F
; Tile index $06E
.db $81 $FE $00 $00 $03 $FC $00 $00 $07 $F8 $00 $00 $0F $F0 $00 $00 $1F $E0 $00 $00 $3F $C0 $00 $00 $7F $80 $00 $00 $FF $00 $00 $00
; Tile index $06F
.db $E1 $58 $47 $3E $E1 $58 $47 $3E $E1 $58 $47 $3F $E0 $1C $43 $3F $F0 $0A $45 $3F $E0 $38 $67 $1F $E0 $7E $21 $1F $F0 $2C $23 $1F
; Tile index $070
.db $3F $20 $0F $1F $1F $00 $0F $1F $3E $01 $3F $1F $A7 $40 $FF $FF $17 $00 $FF $FF $0E $01 $FF $FF $1F $00 $FF $FF $F8 $07 $7F $FF
; Tile index $071
.db $F1 $2C $23 $1E $F1 $0F $21 $1E $F1 $0C $22 $1F $F0 $1E $31 $0F $F8 $16 $11 $0F $F8 $17 $10 $0F $DC $2B $18 $07 $8E $7D $0C $03
; Tile index $072
.db $FF $B1 $4F $00 $BF $38 $AD $02 $4A $15 $A5 $FF $1C $03 $FF $FF $17 $00 $FF $FF $0E $01 $FF $FF $0E $01 $FF $FF $0F $00 $FF $FF
; Tile index $073
.db $FF $AA $FF $00 $FF $00 $AA $55 $55 $AA $AA $FF $00 $FF $FF $FF $FF $00 $FF $FF $55 $AA $FF $FF $55 $AA $FF $FF $FF $00 $FF $FF
; Tile index $074
.db $8F $34 $C4 $78 $8F $F0 $84 $78 $8F $30 $44 $F8 $0F $78 $8C $F0 $1F $68 $88 $F0 $1F $E8 $08 $F0 $3F $D0 $18 $E0 $7F $B0 $30 $C0
; Tile index $075
.db $06 $FD $04 $03 $03 $FF $03 $00 $01 $FE $01 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $076
.db $07 $C0 $3F $FF $83 $60 $1F $FF $C1 $B0 $8F $7F $78 $B6 $71 $0F $1F $E7 $0F $00 $3F $C0 $00 $00 $7F $80 $00 $00 $FF $00 $00 $00
; Tile index $077
.db $FF $00 $FF $FF $FF $00 $FF $FF $AA $00 $FF $FF $00 $55 $AA $FF $FF $FF $FF $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $078
.db $FF $00 $FF $FF $FF $00 $FF $FF $AA $00 $FF $FF $00 $55 $AA $FF $FF $FF $FF $00 $E0 $1F $00 $00 $C0 $3F $00 $00 $80 $7F $00 $00
; Tile index $079
.db $FF $00 $FF $FF $FF $00 $FF $FF $AA $00 $FF $FF $00 $55 $AA $FF $FF $FF $FF $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $07A
.db $FF $00 $FF $FF $FF $00 $FF $FF $AA $00 $FF $FF $00 $55 $AA $FF $FF $FF $FF $00 $3F $C0 $00 $00 $7F $80 $00 $00 $FF $00 $00 $00
; Tile index $07B
.db $E0 $03 $FC $FF $C1 $06 $F8 $FF $83 $0D $F1 $FE $1F $6C $8E $F0 $FF $E0 $F0 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $07C
.db $7F $A0 $20 $C0 $FE $C1 $C0 $00 $FC $03 $80 $00 $F8 $07 $00 $00 $F0 $0F $00 $00 $E0 $1F $00 $00 $C0 $3F $00 $00 $80 $7F $00 $00
; Tile index $07D
.db $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $BF $BF $BF $FF $80 $80 $80 $FF $FF $FF $FF
; Tile index $07E
.db $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $FE $FF $FE $FE $00 $FF $00 $00 $FF $FF $FF $FF
